# Site Settings
title: Alex Trautman
email: alexjtrautman@gmail.com
description: >
  Getting started with Jekyll.
baseurl: ""
url: "http://localhost:4000"
twitter_username: trautmaa
github_username:  trautmaa
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM



# Collections
collections_dir: collections
collections:
  apps:
    output: true
  sections:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      publish: "true"